package org.zwobble.clunk.parser;

public enum TokenType {
    KEYWORD_FALSE,
    KEYWORD_FUN,
    KEYWORD_RECORD,
    KEYWORD_RETURN,
    KEYWORD_TRUE,

    SYMBOL_ARROW,
    SYMBOL_BRACE_OPEN,
    SYMBOL_BRACE_CLOSE,
    SYMBOL_COLON,
    SYMBOL_COMMA,
    SYMBOL_PAREN_OPEN,
    SYMBOL_PAREN_CLOSE,

    IDENTIFIER,
    STRING,

    WHITESPACE,
    UNKNOWN,
    END,
}
